services:
  postgres-fin-app:
    image: postgres:latest
    container_name: postgres-fin-app
    environment:
      POSTGRES_DB: fin_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data