spring:
  application:
    name: FinApp
  mvc:
    servlet:
      path: /api
  ai:
    openai:
      api-key: ${OPEN_API_KEY}

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} userId[%X{user-id}] [%X{transaction-id}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'